CREATE DATABASE TPI_BD2

GO

USE TPI_BD2

GO

CREATE TABLE Usuario(
    IDUsuario INTEGER NOT NULL PRIMARY KEY,
    DNI VARCHAR (20) NOT NULL UNIQUE,
    Nombre VARCHAR (100) NOT NULL,
    Apellido VARCHAR (100) NOT NULL,
    Correo VARCHAR (150) NOT NULL,
    Contrasenia VARCHAR (150) NOT NULL,
    Rol VARCHAR (50) NOT NULL,
    Telefono VARCHAR (20) NOT NULL,
    Direccion VARCHAR (255) NOT NULL,
    CodigoPostal VARCHAR (10) NOT NULL,
    Estado BIT NOT NULL,
)

CREATE TABLE EstadoPedido(
    IDEstado INTEGER NOT NULL PRIMARY KEY,
    Nombre VARCHAR (50),
)

CREATE TABLE MetodoPago(
    IDMetodoPago TINYINT NOT NULL PRIMARY KEY,
    Nombre VARCHAR (50),
)

CREATE TABLE Pedido(
    IDPedido INTEGER NOT NULL PRIMARY KEY,
    IDUsuario INTEGER NOT NULL FOREIGN KEY REFERENCES Usuario (IDUsuario),
    Precio DECIMAL (10,2) NOT NULL,
    IDEstado INTEGER NOT NULL FOREIGN KEY REFERENCES EstadoPedido (IDEstado),
    IDMetodoPago TINYINT NOT NULL FOREIGN KEY REFERENCES MetodoPago (IDMetodoPago),
    FechaPedido DATETIME NOT NULL,
)

CREATE TABLE Marca(
    IDMarca INTEGER NOT NULL PRIMARY KEY,
    Nombre VARCHAR (100) NOT NULL UNIQUE,
)

CREATE TABLE Categoria(
    IDCategoria INTEGER NOT NULL PRIMARY KEY,
    Nombre VARCHAR (100) NOT NULL,
)

CREATE TABLE Producto(
    IDProducto INTEGER NOT NULL PRIMARY KEY,
    Codigo VARCHAR (50) NOT NULL UNIQUE,
    Nombre VARCHAR (100) NOT NULL,
    IDMarca INTEGER NOT NULL FOREIGN KEY REFERENCES Marca (IDMarca),
    IDCategoria INTEGER NOT NULL FOREIGN KEY REFERENCES Categoria (IDCategoria),
    Descripcion TEXT NOT NULL,
    PrecioCompra DECIMAL (10,2) NOT NULL,
    PorcentajeGanancia DECIMAL (5,2) NOT NULL,
    PrecioVenta DECIMAL (10,2) NOT NULL,
    StockAnual INTEGER NOT NULL,
    StockMinimo INTEGER NOT NULL,
    Estado BIT NOT NULL,
)

CREATE TABLE DetalleProducto(
    IDDetalle INTEGER NOT NULL PRIMARY KEY,
    IDProducto INTEGER NOT NULL FOREIGN KEY REFERENCES Producto (IDProducto),
    IDPedido INTEGER NOT NULL FOREIGN KEY REFERENCES Pedido (IDPedido),
    Cantidad INTEGER NOT NULL,
    PrecioUnitario DECIMAL (10,2) NOT NULL,
    PrecioRebajado DECIMAL (10,2) NOT NULL,
)

CREATE TABLE AuditoriaPrecio(
    IDAuditoria INTEGER NOT NULL PRIMARY KEY,
    IDProducto INTEGER NOT NULL FOREIGN KEY REFERENCES Producto (IDProducto),
    PrecioAnterior DECIMAL (10,2) NOT NULL,
    PrecioNuevo DECIMAL (10,2) NOT NULL,
    FechaCambio DATETIME NOT NULL,
)

CREATE TABLE Imagenes(
    IDImagen INTEGER NOT NULL PRIMARY KEY,
    IDProducto INTEGER NOT NULL FOREIGN KEY REFERENCES Producto (IDProducto),
    URL VARCHAR (255) NOT NULL,
)